-- Auto-generated by Matugen

require('base16-colorscheme').setup({
  base00 = '#12140e',
  base01 = '#0d0f09',
  base02 = '#1a1c15',
  base03 = '#45483d',
  base04 = '#c5c8b9',
  base05 = '#e3e3d8',
  base06 = '#2f312a',
  base07 = '#383a32',

  base08 = '#ffb4ab',
  base09 = '#a0d0ca',
  base0A = '#c1caab',
  base0B = '#b5d087',
  base0C = '#1f4e4a',
  base0D = '#384d13',
  base0E = '#414a32',
  base0F = '#93000a',
})


-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
  for _, v in pairs(groups) do
    vim.api.nvim_set_hl(0, v, value)
  end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, 'Visual', {
  bg = '#384d13',
  fg = '#12140e',
})

set_hl_mutliple({ 'TSComment', 'Comment' }, {
  fg = '#bcece6',
})

set_hl_mutliple({ 'TSMethod', 'Method' }, {
  fg = '#a0d0ca',
})

set_hl_mutliple({ 'TSFunction', 'Function' }, {
  fg = '#c1caab',
})

vim.api.nvim_set_hl(0, 'Keyword', {
  fg = '#4f6629',
})

vim.api.nvim_set_hl(0, 'MsgArea', {
  bg = '#0d0f09',
  fg = '#b5d087',
})
