-- Auto-generated by Matugen

require('base16-colorscheme').setup({
  base00 = '#101510',
  base01 = '#0a0f0b',
  base02 = '#181d18',
  base03 = '#414941',
  base04 = '#c1c9bf',
  base05 = '#dfe4dc',
  base06 = '#2d322d',
  base07 = '#353a35',

  base08 = '#ffb4ab',
  base09 = '#a2ced9',
  base0A = '#b6ccb8',
  base0B = '#96d5a6',
  base0C = '#214d57',
  base0D = '#13512d',
  base0E = '#384b3c',
  base0F = '#93000a',
})


-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
  for _, v in pairs(groups) do
    vim.api.nvim_set_hl(0, v, value)
  end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, 'Visual', {
  bg = '#13512d',
  fg = '#101510',
})

set_hl_mutliple({ 'TSComment', 'Comment' }, {
  fg = '#beeaf6',
})

set_hl_mutliple({ 'TSMethod', 'Method' }, {
  fg = '#a2ced9',
})

set_hl_mutliple({ 'TSFunction', 'Function' }, {
  fg = '#b6ccb8',
})

vim.api.nvim_set_hl(0, 'Keyword', {
  fg = '#2f6a43',
})

vim.api.nvim_set_hl(0, 'MsgArea', {
  bg = '#0a0f0b',
  fg = '#96d5a6',
})
